apiVersion: v1
kind: Service
metadata:
  name: serverservice
  labels:
    app: testing-app

spec:
  type: NodePort
  selector:
    tier: server-app-pod
    app: testing-app
  ports:
  - port: 4000
    targetPort: 4000
